/* ===========================================================
   Données géographiques : 46 départements (pour le tracé de la
   carte et les points cliquables) + 553 communes (pour le suivi
   citoyen à proprement parler : statut, maire, référent...).

   Depuis l'Acte III de la décentralisation (loi n° 2013-10 du
   28 décembre 2013), tout le territoire sénégalais est communalisé :
   le Sénégal compte 14 régions, 46 départements (depuis la création
   du département de Keur Massar en 2021) et 557 communes.

   ⚠️ La liste des 553 communes ci-dessous est compilée à partir de
   la page Wikipédia (EN) "Communes of Senegal" (elle-même sourcée
   sur les décrets de création successifs et le découpage post-2013),
   et n'est pas garantie identique aux 557 officielles à l'unité près
   — voir le README, section "Données communales : fiabilité et
   sources", avant toute publication officielle.
   =========================================================== */

/* 46 départements : [nom, région, x, y]. x,y = position sur la carte
   (viewBox 0 0 600 490), projection équirectangulaire de coordonnées
   géographiques réelles des chefs-lieux — voir scripts/project-map.js. */
const DEPARTEMENTS = [
  ["Dakar","Dakar",30.6,226.4],["Pikine","Dakar",35.8,220.5],["Rufisque","Dakar",47.3,224.1],["Guédiawaye","Dakar",34.5,219.1],["Keur Massar","Dakar",43.1,217.5],
  ["Thiès","Thiès",78,217],["Mbour","Thiès",75.8,252.6],["Tivaouane","Thiès",89.1,201.8],
  ["Diourbel","Diourbel",143.3,229.7],["Mbacké","Diourbel",172.7,217.8],["Bambey","Diourbel",123.2,225.8],
  ["Louga","Louga",144,138],["Kébémer","Louga",123.6,159.2],["Linguère","Louga",247,158.6],
  ["Saint-Louis","Saint-Louis",119.5,99.3],["Dagana","Saint-Louis",211,51.5],["Podor","Saint-Louis",262.5,37],
  ["Matam","Matam",419.9,134],["Kanel","Matam",428.2,150.6],["Ranérou Ferlo","Matam",353.9,168.2],
  ["Tambacounda","Tambacounda",381.7,314.9],["Bakel","Tambacounda",493.5,206.4],["Goudiry","Tambacounda",470,275.3],["Koumpentoum","Tambacounda",298.1,294.5],
  ["Kédougou","Kédougou",520.3,431.5],["Salémata","Kédougou",460.7,424.1],["Saraya","Kédougou",559.8,404.9],
  ["Kolda","Kolda",263.4,399.1],["Vélingara","Kolda",339.9,374.5],["Médina Yoro Foulah","Kolda",284.2,360.1],
  ["Sédhiou","Sédhiou",206.1,416.9],["Goudomp","Sédhiou",176.9,429.4],["Bounkiling","Sédhiou",192.8,384.1],
  ["Ziguinchor","Ziguinchor",139.7,428.9],["Bignona","Ziguinchor",143.9,407.1],["Oussouye","Ziguinchor",114.2,438.3],
  ["Fatick","Fatick",126.8,260.4],["Gossas","Fatick",158.9,245.6],["Foundiougne","Fatick",121.6,280.1],
  ["Kaolack","Kaolack",158.2,278.3],["Nioro du Rip","Kaolack",183.5,316.9],["Guinguinéo","Kaolack",169.6,267.3],
  ["Kaffrine","Kaffrine",206.8,282.8],["Birkelane","Kaffrine",185.1,281.7],["Malem Hodar","Kaffrine",230.5,284.4],["Koungheul","Kaffrine",276,296.1]
];

/* Tracé réel des frontières du Sénégal (Natural Earth, admin 0), projeté
   sur le même viewBox et avec la même méthode que les départements ci-dessus. */
const SENEGAL_OUTLINE = "M98.7,331.8 L60.4,257.1 L14,222.9 L54.9,204.7 L99.9,137.3 L121.9,88 L153.8,57.3 L199.9,65.6 L245.3,44.7 L297.1,43.6 L341.5,71.8 L403.2,97.2 L459.4,167.8 L520.7,233.7 L525,293.4 L543.3,348.4 L578.1,375.3 L586,412.4 L581.7,442.3 L568.3,447.7 L517.7,440.2 L510.7,450.8 L490.2,453 L423.4,429.6 L378.6,428.6 L206.9,424.6 L182,435.4 L151.2,432.3 L102,447.9 L86.8,374.3 L171.3,376.4 L193.7,362.9 L210.3,362.1 L244.8,340 L284.6,360.3 L325,362 L365.2,340.4 L346.4,312.7 L315.8,328.8 L286.9,328.4 L250.3,304.8 L220.8,306.3 L199.8,329 L98.7,331.8 Z";

/* 553 communes : [nom, département, région, statut].
   statut : "doc" = à documenter (tout est à "doc" par défaut : aucune
   démarche réelle n'a encore été engagée par le réseau de référents)
   "env" = demande envoyée · "obt" = réponse obtenue · "ref" = refus opposé */
const COMMUNES = [
  ["Biscuiterie","Dakar","Dakar","doc"],["Cambérène","Dakar","Dakar","doc"],["Colobane / Fass / Gueule Tapée","Dakar","Dakar","doc"],["Dakar-Plateau","Dakar","Dakar","doc"],["Dieuppeul-Derklé","Dakar","Dakar","doc"],["Fann-Point E-Amitié","Dakar","Dakar","doc"],["Gorée","Dakar","Dakar","doc"],["Grand Dakar","Dakar","Dakar","doc"],["Grand Yoff","Dakar","Dakar","env"],["Hann Bel-Air","Dakar","Dakar","doc"],["HLM","Dakar","Dakar","doc"],["Médina","Dakar","Dakar","doc"],["Mermoz-Sacré-Cœur","Dakar","Dakar","doc"],["Ngor","Dakar","Dakar","doc"],["Ouakam","Dakar","Dakar","doc"],["Parcelles Assainies","Dakar","Dakar","doc"],["Patte d'Oie","Dakar","Dakar","doc"],["Sicap-Liberté","Dakar","Dakar","doc"],["Yoff","Dakar","Dakar","doc"],
  ["Golf Sud","Guédiawaye","Dakar","doc"],["Médina Gounass","Guédiawaye","Dakar","doc"],["Ndiarème Limamoulaye","Guédiawaye","Dakar","doc"],["Sam Notaire","Guédiawaye","Dakar","doc"],["Wakhinane Nimzatt","Guédiawaye","Dakar","doc"],
  ["Dalifort","Pikine","Dakar","doc"],["Diacksao","Pikine","Dakar","doc"],["Diamaguène / Sicap Mbao","Pikine","Dakar","doc"],["Djidah Thiaroye Kaw","Pikine","Dakar","doc"],["Guinaw Rail Nord","Pikine","Dakar","doc"],["Guinaw Rail Sud","Pikine","Dakar","doc"],["Mbao","Pikine","Dakar","doc"],["Pikine Est","Pikine","Dakar","doc"],["Pikine Ouest","Pikine","Dakar","doc"],["Pikine Sud","Pikine","Dakar","doc"],["Thiaroye-Gare","Pikine","Dakar","doc"],["Thiaroye-sur-Mer","Pikine","Dakar","doc"],
  ["Bambylor","Rufisque","Dakar","doc"],["Bargny","Rufisque","Dakar","doc"],["Diamniadio","Rufisque","Dakar","doc"],["Rufisque Est","Rufisque","Dakar","doc"],["Rufisque Nord","Rufisque","Dakar","doc"],["Rufisque Ouest","Rufisque","Dakar","doc"],["Sangalkam","Rufisque","Dakar","doc"],["Sébikhotane","Rufisque","Dakar","doc"],["Sendou","Rufisque","Dakar","doc"],["Tivaouane Peulh-Niaga","Rufisque","Dakar","doc"],["Yène","Rufisque","Dakar","doc"],
  ["Jaxaay-Parcelles","Keur Massar","Dakar","doc"],["Keur Massar Nord","Keur Massar","Dakar","doc"],["Keur Massar Sud","Keur Massar","Dakar","doc"],["Malika","Keur Massar","Dakar","doc"],["Yeumbeul Nord","Keur Massar","Dakar","doc"],["Yeumbeul Sud","Keur Massar","Dakar","doc"],
  ["Baba Garage","Bambey","Diourbel","doc"],["Bambey","Bambey","Diourbel","doc"],["Dinguiraye","Bambey","Diourbel","doc"],["Gawane","Bambey","Diourbel","doc"],["Keur Samba Kane","Bambey","Diourbel","doc"],["Lambaye","Bambey","Diourbel","doc"],["Ndangalma","Bambey","Diourbel","doc"],["Ndondol","Bambey","Diourbel","doc"],["Ngogom","Bambey","Diourbel","doc"],["Ngoye","Bambey","Diourbel","doc"],["Réfane","Bambey","Diourbel","doc"],["Thiakhar","Bambey","Diourbel","doc"],
  ["Diourbel","Diourbel","Diourbel","doc"],["Gade Escale","Diourbel","Diourbel","doc"],["Keur Ngalgou","Diourbel","Diourbel","doc"],["Dankh Sène","Diourbel","Diourbel","doc"],["Ndindy","Diourbel","Diourbel","doc"],["Ndoulo","Diourbel","Diourbel","doc"],["Ngohé","Diourbel","Diourbel","doc"],["Patar","Diourbel","Diourbel","doc"],["Taïba Moutoupha","Diourbel","Diourbel","doc"],["Tocky-Gare","Diourbel","Diourbel","doc"],["Touba Lappé","Diourbel","Diourbel","doc"],["Touré Mbonde","Diourbel","Diourbel","doc"],
  ["Dalla Ngabou","Mbacké","Diourbel","doc"],["Darou Nahim","Mbacké","Diourbel","doc"],["Darou Salam Typ","Mbacké","Diourbel","doc"],["Dendey Gouyegui","Mbacké","Diourbel","doc"],["Kael","Mbacké","Diourbel","doc"],["Madina","Mbacké","Diourbel","doc"],["Mbacké","Mbacké","Diourbel","doc"],["Missirah","Mbacké","Diourbel","doc"],["Ndioumane","Mbacké","Diourbel","doc"],["Nghaye","Mbacké","Diourbel","doc"],["Sadio","Mbacké","Diourbel","doc"],["Taïba Thiékène","Mbacké","Diourbel","doc"],["Taïf","Mbacké","Diourbel","doc"],["Touba Fall","Mbacké","Diourbel","doc"],["Touba Mboul","Mbacké","Diourbel","doc"],["Touba Mosquée","Mbacké","Diourbel","doc"],
  ["Diakhao","Fatick","Fatick","doc"],["Diaoulé","Fatick","Fatick","doc"],["Diarrère","Fatick","Fatick","doc"],["Diofior","Fatick","Fatick","doc"],["Diouroup","Fatick","Fatick","doc"],["Djilasse","Fatick","Fatick","doc"],["Fatick","Fatick","Fatick","doc"],["Fimela","Fatick","Fatick","doc"],["Loul Séssène","Fatick","Fatick","doc"],["Mbéllacadiao","Fatick","Fatick","doc"],["Ndiob","Fatick","Fatick","doc"],["Ngayokhème","Fatick","Fatick","doc"],["Niakhar","Fatick","Fatick","doc"],["Palmarin","Fatick","Fatick","doc"],["Patar","Fatick","Fatick","doc"],["Tattaguine","Fatick","Fatick","doc"],["Thiaré Ndialgui","Fatick","Fatick","doc"],
  ["Bassoul","Foundiougne","Fatick","doc"],["Diagane Barka","Foundiougne","Fatick","doc"],["Dionewar","Foundiougne","Fatick","doc"],["Diossong","Foundiougne","Fatick","doc"],["Djilor","Foundiougne","Fatick","doc"],["Djirnda","Foundiougne","Fatick","doc"],["Foundiougne","Foundiougne","Fatick","doc"],["Karang Poste","Foundiougne","Fatick","doc"],["Keur Saloum Diané","Foundiougne","Fatick","doc"],["Keur Samba Guèye","Foundiougne","Fatick","doc"],["Mbam","Foundiougne","Fatick","doc"],["Niassène","Foundiougne","Fatick","doc"],["Nioro Alassane Tall","Foundiougne","Fatick","doc"],["Passy","Foundiougne","Fatick","doc"],["Sokone","Foundiougne","Fatick","doc"],["Soum","Foundiougne","Fatick","doc"],["Toubacouta","Foundiougne","Fatick","doc"],
  ["Colobane","Gossas","Fatick","doc"],["Gossas","Gossas","Fatick","doc"],["Mbar","Gossas","Fatick","doc"],["Ndiène Lagane","Gossas","Fatick","doc"],["Ouadiour","Gossas","Fatick","doc"],["Patar Lia","Gossas","Fatick","doc"],
  ["Birkilane","Birkelane","Kaffrine","doc"],["Diamal","Birkelane","Kaffrine","doc"],["Keur Mboucki","Birkelane","Kaffrine","doc"],["Mabo","Birkelane","Kaffrine","doc"],["Mbeuleup","Birkelane","Kaffrine","doc"],["Ndiognick","Birkelane","Kaffrine","doc"],["Ségré Gatta","Birkelane","Kaffrine","doc"],["Touba Mbella","Birkelane","Kaffrine","doc"],
  ["Boulel","Kaffrine","Kaffrine","doc"],["Diamagadio","Kaffrine","Kaffrine","doc"],["Diokoul Mbelbouck","Kaffrine","Kaffrine","doc"],["Gniby","Kaffrine","Kaffrine","doc"],["Kaffrine","Kaffrine","Kaffrine","doc"],["Kahi","Kaffrine","Kaffrine","doc"],["Kathiotte","Kaffrine","Kaffrine","doc"],["Médinatoul Salam II","Kaffrine","Kaffrine","doc"],["Nganda","Kaffrine","Kaffrine","doc"],
  ["Fass Thiékène","Koungheul","Kaffrine","doc"],["Ida Mouride","Koungheul","Kaffrine","doc"],["Koungheul","Koungheul","Kaffrine","doc"],["Lour Escale","Koungheul","Kaffrine","doc"],["Maka Yop","Koungheul","Kaffrine","doc"],["Missirah Wadène","Koungheul","Kaffrine","doc"],["Gainte Pathé","Koungheul","Kaffrine","doc"],["Ribot Escale","Koungheul","Kaffrine","doc"],["Saly Escale","Koungheul","Kaffrine","doc"],
  ["Darou Minam 2","Malem Hodar","Kaffrine","doc"],["Dianké Souf","Malem Hodar","Kaffrine","doc"],["Khelcom","Malem Hodar","Kaffrine","doc"],["Malem-Hodar","Malem Hodar","Kaffrine","doc"],["Ndiobène Samba Lamo","Malem Hodar","Kaffrine","doc"],["Ndioum Ngainthe","Malem Hodar","Kaffrine","doc"],["Sagna","Malem Hodar","Kaffrine","doc"],
  ["Dara Mboss","Guinguinéo","Kaolack","doc"],["Fass","Guinguinéo","Kaolack","doc"],["Gagnick","Guinguinéo","Kaolack","doc"],["Guinguinéo","Guinguinéo","Kaolack","doc"],["Khelcom Birane","Guinguinéo","Kaolack","doc"],["Mbadakhoune","Guinguinéo","Kaolack","doc"],["Mboss","Guinguinéo","Kaolack","doc"],["Ndiago","Guinguinéo","Kaolack","doc"],["Ngathe Naoudé","Guinguinéo","Kaolack","doc"],["Nguélou","Guinguinéo","Kaolack","doc"],["Ourour","Guinguinéo","Kaolack","doc"],["Panal Wolof","Guinguinéo","Kaolack","doc"],
  ["Dya","Kaolack","Kaolack","doc"],["Gandiaye","Kaolack","Kaolack","doc"],["Kahone","Kaolack","Kaolack","doc"],["Kaolack","Kaolack","Kaolack","doc"],["Keur Baka","Kaolack","Kaolack","doc"],["Latmingué","Kaolack","Kaolack","doc"],["Ndiaffate","Kaolack","Kaolack","doc"],["Ndiébel","Kaolack","Kaolack","doc"],["Ndiédieng","Kaolack","Kaolack","doc"],["Ndofane","Kaolack","Kaolack","doc"],["Sibassor","Kaolack","Kaolack","doc"],["Thiaré","Kaolack","Kaolack","doc"],["Thiomby","Kaolack","Kaolack","doc"],
  ["Dabaly","Nioro du Rip","Kaolack","doc"],["Darou Salam","Nioro du Rip","Kaolack","doc"],["Gainthe Kaye","Nioro du Rip","Kaolack","doc"],["Kayemor","Nioro du Rip","Kaolack","doc"],["Keur Maba Diakhou","Nioro du Rip","Kaolack","doc"],["Keur Madiabel","Nioro du Rip","Kaolack","doc"],["Keur Madongo","Nioro du Rip","Kaolack","doc"],["Keur Socé","Nioro du Rip","Kaolack","doc"],["Médina Sabakh","Nioro du Rip","Kaolack","doc"],["Ndramé Escale","Nioro du Rip","Kaolack","doc"],["Ngayène","Nioro du Rip","Kaolack","doc"],["Nioro du Rip","Nioro du Rip","Kaolack","doc"],["Paoskoto","Nioro du Rip","Kaolack","doc"],["Porokhane","Nioro du Rip","Kaolack","doc"],["Taïba Niassène","Nioro du Rip","Kaolack","doc"],["Wack Ngouna","Nioro du Rip","Kaolack","doc"],
  ["Bandafassi","Kédougou","Kédougou","doc"],["Dimboli","Kédougou","Kédougou","doc"],["Dindefelo","Kédougou","Kédougou","doc"],["Fongolimbi","Kédougou","Kédougou","doc"],["Kédougou","Kédougou","Kédougou","doc"],["Ninéfécha","Kédougou","Kédougou","doc"],["Tomboroncoto","Kédougou","Kédougou","doc"],
  ["Dar Salam","Salémata","Kédougou","doc"],["Ethiolo","Salémata","Kédougou","doc"],["Oubadji","Salémata","Kédougou","doc"],["Salémata","Salémata","Kédougou","doc"],
  ["Bembou","Saraya","Kédougou","doc"],["Dakateli","Saraya","Kédougou","doc"],["Kévoye","Saraya","Kédougou","doc"],["Khossanto","Saraya","Kédougou","doc"],["Médina Baffé","Saraya","Kédougou","doc"],["Missirah Sirimana","Saraya","Kédougou","doc"],["Sabodala","Saraya","Kédougou","doc"],["Saraya","Saraya","Kédougou","doc"],
  ["Bagadadji","Kolda","Kolda","doc"],["Coumbacara","Kolda","Kolda","doc"],["Dabo","Kolda","Kolda","doc"],["Dialambéré","Kolda","Kolda","doc"],["Dioulacolon","Kolda","Kolda","doc"],["Guiro Yéro Bocar","Kolda","Kolda","doc"],["Kolda","Kolda","Kolda","doc"],["Mampatim","Kolda","Kolda","doc"],["Médina Chérif","Kolda","Kolda","doc"],["Médina El Hadj","Kolda","Kolda","doc"],["Salikégné","Kolda","Kolda","doc"],["Saré Bidji","Kolda","Kolda","doc"],["Saré Yoba Diéga","Kolda","Kolda","doc"],["Tankanto Escale","Kolda","Kolda","doc"],["Thiétty","Kolda","Kolda","doc"],
  ["Bignarabé","Médina Yoro Foulah","Kolda","doc"],["Bourouco","Médina Yoro Foulah","Kolda","doc"],["Dinguiraye","Médina Yoro Foulah","Kolda","doc"],["Kéréwane","Médina Yoro Foulah","Kolda","doc"],["Koulinto","Médina Yoro Foulah","Kolda","doc"],["Médina Yoro Foulah","Médina Yoro Foulah","Kolda","doc"],["Ndorna","Médina Yoro Foulah","Kolda","doc"],["Niaming","Médina Yoro Foulah","Kolda","doc"],["Pata","Médina Yoro Foulah","Kolda","doc"],
  ["Badion","Vélingara","Kolda","doc"],["Bonconto","Vélingara","Kolda","doc"],["Diaobé-Kabendou","Vélingara","Kolda","doc"],["Fafacourou","Vélingara","Kolda","doc"],["Kandia","Vélingara","Kolda","doc"],["Kandiaye","Vélingara","Kolda","doc"],["Kounkané","Vélingara","Kolda","doc"],["Linkéring","Vélingara","Kolda","doc"],["Médina Gounass","Vélingara","Kolda","doc"],["Némataba","Vélingara","Kolda","doc"],["Ouassadou","Vélingara","Kolda","doc"],["Pakour","Vélingara","Kolda","doc"],["Paroumba","Vélingara","Kolda","doc"],["Saré Coly Sallé","Vélingara","Kolda","doc"],["Sinthiang Koundara","Vélingara","Kolda","doc"],["Vélingara","Vélingara","Kolda","doc"],
  ["Bandegne Ouolof","Kébémer","Louga","doc"],["Darou Marnane","Kébémer","Louga","doc"],["Darou Mousty","Kébémer","Louga","doc"],["Diokoul Diawrigne","Kébémer","Louga","doc"],["Guéoul","Kébémer","Louga","doc"],["Kab Gaye","Kébémer","Louga","doc"],["Kanène Ndiob","Kébémer","Louga","doc"],["Kébémer","Kébémer","Louga","doc"],["Loro","Kébémer","Louga","doc"],["Mbacké Cajor","Kébémer","Louga","doc"],["Mbadiane","Kébémer","Louga","doc"],["Ndande","Kébémer","Louga","doc"],["Ndoyene","Kébémer","Louga","doc"],["Ngourane Ouolof","Kébémer","Louga","doc"],["Sagatta Gueth","Kébémer","Louga","doc"],["Sam Yabal","Kébémer","Louga","doc"],["Thieppe","Kébémer","Louga","doc"],["Thiolom Fall","Kébémer","Louga","doc"],["Touba Mérina","Kébémer","Louga","doc"],
  ["Affé Djoloff","Linguère","Louga","doc"],["Barkédji","Linguère","Louga","doc"],["Boulal","Linguère","Louga","doc"],["Dahra","Linguère","Louga","doc"],["Dealy","Linguère","Louga","doc"],["Dodji","Linguère","Louga","doc"],["Gassane","Linguère","Louga","doc"],["Kamb","Linguère","Louga","doc"],["Labgar","Linguère","Louga","doc"],["Linguère","Linguère","Louga","doc"],["Mbeuleukhé","Linguère","Louga","doc"],["Mboula","Linguère","Louga","doc"],["Ouarkhokh","Linguère","Louga","doc"],["Sagatta Djolof","Linguère","Louga","doc"],["Téssékéré Forage","Linguère","Louga","doc"],["Thiamène Djolof","Linguère","Louga","doc"],["Thiarny","Linguère","Louga","doc"],["Thiel","Linguère","Louga","doc"],["Yang-Yang","Linguère","Louga","doc"],
  ["Coki","Louga","Louga","doc"],["Gande","Louga","Louga","doc"],["Guet Ardo","Louga","Louga","doc"],["Kéle Gueye","Louga","Louga","doc"],["Keur Momar Sarr","Louga","Louga","doc"],["Léona","Louga","Louga","doc"],["Louga","Louga","Louga","doc"],["Mbédiène","Louga","Louga","doc"],["Ndiagne","Louga","Louga","doc"],["Nguer Malal","Louga","Louga","doc"],["Ngueune Sarr","Louga","Louga","doc"],["Nguidilé","Louga","Louga","doc"],["Niomré","Louga","Louga","doc"],["Pété Ouarack","Louga","Louga","doc"],["Sakal","Louga","Louga","doc"],["Syer","Louga","Louga","doc"],["Thiamène Cayor","Louga","Louga","doc"],
  ["Aouré","Kanel","Matam","doc"],["Bokiladji","Kanel","Matam","doc"],["Dembancané","Kanel","Matam","doc"],["Hamady Ounaré","Kanel","Matam","doc"],["Kanel","Kanel","Matam","doc"],["Ndendory","Kanel","Matam","doc"],["Odobéré","Kanel","Matam","doc"],["Orkadiere","Kanel","Matam","doc"],["Semmé","Kanel","Matam","doc"],["Sinthiou Bamambé-Banadji","Kanel","Matam","doc"],["Waoundé","Kanel","Matam","doc"],["Wouro Sidy","Kanel","Matam","doc"],
  ["Agnams","Matam","Matam","doc"],["Bokidiawé","Matam","Matam","doc"],["Dabia","Matam","Matam","doc"],["Matam","Matam","Matam","doc"],["Nabadji Civol","Matam","Matam","doc"],["Nguidjilone","Matam","Matam","doc"],["Ogo","Matam","Matam","doc"],["Oréfondé","Matam","Matam","doc"],["Ourossogui","Matam","Matam","doc"],["Thilogne","Matam","Matam","doc"],
  ["Lougré Thioly","Ranérou Ferlo","Matam","doc"],["Oudalaye","Ranérou Ferlo","Matam","doc"],["Ranérou","Ranérou Ferlo","Matam","doc"],["Vélingara Ferlo","Ranérou Ferlo","Matam","doc"],
  ["Bokhol","Dagana","Saint-Louis","doc"],["Dagana","Dagana","Saint-Louis","doc"],["Diama","Dagana","Saint-Louis","doc"],["Gaé","Dagana","Saint-Louis","doc"],["Mbane","Dagana","Saint-Louis","doc"],["Ndombo Sandjiry","Dagana","Saint-Louis","doc"],["Ngnith","Dagana","Saint-Louis","doc"],["Richard-Toll","Dagana","Saint-Louis","doc"],["Ronkh","Dagana","Saint-Louis","doc"],["Ross Béthio","Dagana","Saint-Louis","doc"],["Rosso","Dagana","Saint-Louis","doc"],
  ["Aéré Lao","Podor","Saint-Louis","doc"],["Bodé Lao","Podor","Saint-Louis","doc"],["Boké Dialloubé","Podor","Saint-Louis","doc"],["Démette","Podor","Saint-Louis","doc"],["Dodel","Podor","Saint-Louis","doc"],["Doumga Lao","Podor","Saint-Louis","doc"],["Fanaye","Podor","Saint-Louis","doc"],["Galoya Toucouleur","Podor","Saint-Louis","doc"],["Gamadji Saré","Podor","Saint-Louis","doc"],["Golléré","Podor","Saint-Louis","doc"],["Guédé Chantier","Podor","Saint-Louis","doc"],["Guédé Village","Podor","Saint-Louis","doc"],["Madina Diathbé","Podor","Saint-Louis","doc"],["Mbolo Birane","Podor","Saint-Louis","doc"],["Mboumba","Podor","Saint-Louis","doc"],["Méry","Podor","Saint-Louis","doc"],["Ndiandane","Podor","Saint-Louis","doc"],["Ndiayène Peindao","Podor","Saint-Louis","doc"],["Ndioum","Podor","Saint-Louis","doc"],["Pété","Podor","Saint-Louis","doc"],["Podor","Podor","Saint-Louis","doc"],["Walaldé","Podor","Saint-Louis","doc"],
  ["Fass Ngom","Saint-Louis","Saint-Louis","doc"],["Gandon","Saint-Louis","Saint-Louis","doc"],["Mpal","Saint-Louis","Saint-Louis","doc"],["Ndiébène Gandiole","Saint-Louis","Saint-Louis","doc"],["Saint-Louis","Saint-Louis","Saint-Louis","doc"],
  ["Bona","Bounkiling","Sédhiou","doc"],["Bounkiling","Bounkiling","Sédhiou","doc"],["Diacounda","Bounkiling","Sédhiou","doc"],["Diambati","Bounkiling","Sédhiou","doc"],["Diaroumé","Bounkiling","Sédhiou","doc"],["Djinany","Bounkiling","Sédhiou","doc"],["Faoune","Bounkiling","Sédhiou","doc"],["Inor","Bounkiling","Sédhiou","doc"],["Kandion Mangana","Bounkiling","Sédhiou","doc"],["Madina Wandifa","Bounkiling","Sédhiou","doc"],["Ndiamacouta","Bounkiling","Sédhiou","doc"],["Ndiamalathiel","Bounkiling","Sédhiou","doc"],["Tankon","Bounkiling","Sédhiou","doc"],
  ["Baghère","Goudomp","Sédhiou","doc"],["Diattacounda","Goudomp","Sédhiou","doc"],["Diouboudou","Goudomp","Sédhiou","doc"],["Djibanar","Goudomp","Sédhiou","doc"],["Goudomp","Goudomp","Sédhiou","doc"],["Kaour","Goudomp","Sédhiou","doc"],["Karantaba","Goudomp","Sédhiou","doc"],["Kolibantang","Goudomp","Sédhiou","doc"],["Mangaroungou Santo","Goudomp","Sédhiou","doc"],["Niagha","Goudomp","Sédhiou","doc"],["Samine","Goudomp","Sédhiou","doc"],["Simbandi Balante","Goudomp","Sédhiou","doc"],["Simbandi Brassou","Goudomp","Sédhiou","doc"],["Tanaff","Goudomp","Sédhiou","doc"],["Yarang Balante","Goudomp","Sédhiou","doc"],
  ["Bambaly","Sédhiou","Sédhiou","doc"],["Bémet Bidjini","Sédhiou","Sédhiou","doc"],["Boghall","Sédhiou","Sédhiou","doc"],["Diannah Ba","Sédhiou","Sédhiou","doc"],["Diannah Malary","Sédhiou","Sédhiou","doc"],["Diendé","Sédhiou","Sédhiou","doc"],["Djibabouya","Sédhiou","Sédhiou","doc"],["Djiredji","Sédhiou","Sédhiou","doc"],["Koussy","Sédhiou","Sédhiou","doc"],["Marsassoum","Sédhiou","Sédhiou","doc"],["Oudoucar","Sédhiou","Sédhiou","doc"],["Sakar","Sédhiou","Sédhiou","doc"],["Sama Kanta Peulh","Sédhiou","Sédhiou","doc"],["Sansamba","Sédhiou","Sédhiou","doc"],["Sédhiou","Sédhiou","Sédhiou","doc"],
  ["Bakel","Bakel","Tambacounda","doc"],["Ballou","Bakel","Tambacounda","doc"],["Bélé","Bakel","Tambacounda","doc"],["Diawara","Bakel","Tambacounda","doc"],["Gabou","Bakel","Tambacounda","doc"],["Gathiary","Bakel","Tambacounda","doc"],["Kidira","Bakel","Tambacounda","doc"],["Madina Foulbé","Bakel","Tambacounda","doc"],["Moudéry","Bakel","Tambacounda","doc"],["Sadatou","Bakel","Tambacounda","doc"],["Sinthiou Fissa","Bakel","Tambacounda","doc"],["Toumboura","Bakel","Tambacounda","doc"],
  ["Bala","Goudiry","Tambacounda","doc"],["Bani Israël","Goudiry","Tambacounda","doc"],["Boutoucoufara","Goudiry","Tambacounda","doc"],["Boynguel Bamba","Goudiry","Tambacounda","doc"],["Dianké Makha","Goudiry","Tambacounda","doc"],["Dougué","Goudiry","Tambacounda","doc"],["Goumbayél","Goudiry","Tambacounda","doc"],["Goudiry","Goudiry","Tambacounda","doc"],["Koar","Goudiry","Tambacounda","doc"],["Komoti","Goudiry","Tambacounda","doc"],["Kothiary","Goudiry","Tambacounda","doc"],["Koulor","Goudiry","Tambacounda","doc"],["Koussan","Goudiry","Tambacounda","doc"],["Sinthiou Bocar Ali","Goudiry","Tambacounda","doc"],["Sinthiou Mamadou Boubou","Goudiry","Tambacounda","doc"],
  ["Bamba Thialène","Koumpentoum","Tambacounda","doc"],["Kahène","Koumpentoum","Tambacounda","doc"],["Koumpentoum","Koumpentoum","Tambacounda","doc"],["Kouthia Gaydi","Koumpentoum","Tambacounda","doc"],["Kouthiaba Wolof","Koumpentoum","Tambacounda","doc"],["Malem Niani","Koumpentoum","Tambacounda","doc"],["Méréto","Koumpentoum","Tambacounda","doc"],["Ndame","Koumpentoum","Tambacounda","doc"],["Niani Toucouleur","Koumpentoum","Tambacounda","doc"],["Pass Koto","Koumpentoum","Tambacounda","doc"],["Payar","Koumpentoum","Tambacounda","doc"],["Sinthiou Malème","Koumpentoum","Tambacounda","doc"],
  ["Dialacoto","Tambacounda","Tambacounda","doc"],["Koussanar","Tambacounda","Tambacounda","doc"],["Makacolibantang","Tambacounda","Tambacounda","doc"],["Missirah","Tambacounda","Tambacounda","doc"],["Ndoga Babacar","Tambacounda","Tambacounda","doc"],["Néttéboulou","Tambacounda","Tambacounda","doc"],["Tambacounda","Tambacounda","Tambacounda","doc"],
  ["Diass","Mbour","Thiès","doc"],["Fissel","Mbour","Thiès","doc"],["Joal-Fadiouth","Mbour","Thiès","doc"],["Mbour","Mbour","Thiès","doc"],["Malicounda","Mbour","Thiès","doc"],["Ndiaganiao","Mbour","Thiès","doc"],["Ngaparou","Mbour","Thiès","doc"],["Nguékhokh","Mbour","Thiès","doc"],["Nguéniène","Mbour","Thiès","doc"],["Popenguine-Ndayane","Mbour","Thiès","doc"],["Saly","Mbour","Thiès","doc"],["Sandiara","Mbour","Thiès","doc"],["Séssène","Mbour","Thiès","doc"],["Sindia","Mbour","Thiès","doc"],["Somone","Mbour","Thiès","doc"],["Thiadiaye","Mbour","Thiès","doc"],
  ["Diender","Thiès","Thiès","doc"],["Fandène","Thiès","Thiès","doc"],["Kayar","Thiès","Thiès","doc"],["Keur Moussa","Thiès","Thiès","doc"],["Khombole","Thiès","Thiès","doc"],["Ndiéyène Sirah","Thiès","Thiès","doc"],["Ngoudiane","Thiès","Thiès","doc"],["Notto","Thiès","Thiès","doc"],["Pout","Thiès","Thiès","doc"],["Tassette","Thiès","Thiès","doc"],["Thiénaba","Thiès","Thiès","doc"],["Thiès Est","Thiès","Thiès","doc"],["Thiès Nord","Thiès","Thiès","doc"],["Thiès Ouest","Thiès","Thiès","doc"],["Touba Toul","Thiès","Thiès","doc"],["Yaboyabo","Thiès","Thiès","doc"],
  ["Chérif Lo","Tivaouane","Thiès","doc"],["Darou Khoudoss","Tivaouane","Thiès","doc"],["Koul","Tivaouane","Thiès","doc"],["Mbayène","Tivaouane","Thiès","doc"],["Mboro","Tivaouane","Thiès","doc"],["Meckhe","Tivaouane","Thiès","doc"],["Méouane","Tivaouane","Thiès","doc"],["Mérina Dakhar","Tivaouane","Thiès","doc"],["Mont Rolland","Tivaouane","Thiès","doc"],["Ngandiouf","Tivaouane","Thiès","doc"],["Niakhene","Tivaouane","Thiès","doc"],["Notto Gouye Diama","Tivaouane","Thiès","doc"],["Pambal","Tivaouane","Thiès","doc"],["Pékèsse","Tivaouane","Thiès","doc"],["Pire Goureye","Tivaouane","Thiès","doc"],["Taïba Ndiaye","Tivaouane","Thiès","doc"],["Thilmakha","Tivaouane","Thiès","doc"],["Tivaouane","Tivaouane","Thiès","doc"],
  ["Balinghore","Bignona","Ziguinchor","doc"],["Bignona","Bignona","Ziguinchor","doc"],["Boutoupa-Camaracounda","Bignona","Ziguinchor","doc"],["Diégoune","Bignona","Ziguinchor","doc"],["Diouloulou","Bignona","Ziguinchor","doc"],["Djibidione","Bignona","Ziguinchor","doc"],["Djinaky","Bignona","Ziguinchor","doc"],["Kafountine","Bignona","Ziguinchor","doc"],["Kartiack","Bignona","Ziguinchor","doc"],["Kataba 1","Bignona","Ziguinchor","doc"],["Mangagoulack","Bignona","Ziguinchor","doc"],["Niamone","Bignona","Ziguinchor","doc"],["Oulampane","Bignona","Ziguinchor","doc"],["Ouonck","Bignona","Ziguinchor","doc"],["Sindian","Bignona","Ziguinchor","doc"],["Suelle","Bignona","Ziguinchor","doc"],["Tenghory","Bignona","Ziguinchor","doc"],["Thionck Essyl","Bignona","Ziguinchor","doc"],
  ["Diembéring","Oussouye","Ziguinchor","doc"],["Enampore","Oussouye","Ziguinchor","doc"],["Mlomp","Oussouye","Ziguinchor","doc"],["Oukout","Oussouye","Ziguinchor","doc"],["Oussouye","Oussouye","Ziguinchor","doc"],["Santhiaba Manjacque","Oussouye","Ziguinchor","doc"],
  ["Adéane","Ziguinchor","Ziguinchor","doc"],["Coubalan","Ziguinchor","Ziguinchor","doc"],["Niaguis","Ziguinchor","Ziguinchor","doc"],["Nyassia","Ziguinchor","Ziguinchor","doc"],["Ziguinchor","Ziguinchor","Ziguinchor","doc"]
];

/* Fiches détaillées par commune, clé "Nom|Département" (certains noms de
   commune se répètent dans des départements différents — ex. deux
   communes nommées "Vélingara" existent, l'une chef-lieu du département
   de Vélingara, l'autre dans Ranérou Ferlo — d'où la clé composite).

   Ces maires (élections locales du 23 janvier 2022, avec remplacements
   connus depuis) proviennent de recherches documentaires et PEUVENT ÊTRE
   DÉSUÈTES ou inexactes : à vérifier par le réseau de référents avant
   toute publication officielle. Limité aux grandes communes/villes pour
   lesquelles une source a été trouvée — la grande majorité des 553
   communes n'a pas de maire renseigné (aucune base de données publique
   centralisée des résultats commune par commune n'a été identifiée). */
const COMMUNE_DETAILS = {
  "Bargny|Rufisque": { maire: "Djibril Fall", note: "Élu en janvier 2022." },
  "Tivaouane|Tivaouane": { maire: "Demba Diop (dit Diop Sy)", note: "Élu en janvier 2022.", referent: "Bassirou Dieng, Mbaye Ndiaye" },
  "Joal-Fadiouth|Mbour": { maire: "Sophie Gladima", note: "Élue en janvier 2022." },
  "Diourbel|Diourbel": { maire: "Malick Fall", note: "Élu en janvier 2022.", referent: "Sileymane Diao" },
  "Mbacké|Mbacké": { maire: "Gallo Bâ", note: "Élu en janvier 2022." },
  "Louga|Louga": { maire: "Moustapha Diop", note: "Élu en janvier 2022.", referent: "Mouhameth Sarr" },
  "Saint-Louis|Saint-Louis": { maire: "Mansour Faye", note: "Réélu en janvier 2022, en poste." },
  "Richard-Toll|Dagana": { maire: "Amadou Mame Diop", note: "Élu en janvier 2022." },
  "Tambacounda|Tambacounda": { maire: "Papa Banda Dièye", note: "Élu en janvier 2022." },
  "Kédougou|Kédougou": { maire: "Ousmane Sylla", note: "Élu en janvier 2022." },
  "Kolda|Kolda": { maire: "Mame Boye Diao", note: "Élu en janvier 2022.", referent: "Balde Bilal" },
  "Vélingara|Vélingara": { maire: "Mamadou Oury Baïlo Diallo", note: "Réélu (4ᵉ mandat consécutif) en janvier 2022." },
  "Sédhiou|Sédhiou": { maire: "Abdoulaye Diop", note: "Élu en janvier 2022." },
  "Ziguinchor|Ziguinchor": { maire: "Djibril Sonko", note: "Élu en juin 2024, après la démission d'Ousmane Sonko (devenu Premier ministre).", referent: "Awa Ly, Ismael E. Badji, Youssouph Ndiaye" },
  "Kaffrine|Kaffrine": { maire: "Abdoulaye Saydou Sow", note: "Élu en janvier 2022." },
  "Kaolack|Kaolack": { maire: "Sérigne Mboup", note: "Élu en janvier 2022.", referent: "Cheikh Ahmad Tidiane Ndao" },
  "Gossas|Gossas": { maire: "Adama Diallo", note: "Élu en janvier 2022." },
  "Fatick|Fatick": { maire: "Matar Bâ", note: "Élu en janvier 2022 — mandat à reconfirmer." },
  "Foundiougne|Foundiougne": { maire: "Thiémokho Ndiaye", note: "Source à recouper." },
  "Nioro du Rip|Nioro du Rip": { maire: "Modou Mbaye", note: "Source à recouper." },
  "Guinguinéo|Guinguinéo": { maire: "Rokhaya Diouf", note: "Source à recouper." },
  "Mbour|Mbour": { maire: "Cheikh Issa Sall", note: "Élu en janvier 2022.", referent: "Pape Moussa Diome" },
  "Kayar|Thiès": { maire: "Alioune Ndoye", note: "Sources divergentes : l'ancien maire Ndiassé Kâ est décédé en cours de mandat — à reconfirmer." },
  "Mboro|Tivaouane": { maire: "Abdallah Tall", note: "En poste en 2022.", referent: "Ba Mamadou" },
  "Khombole|Thiès": { maire: "Maguéye Boye", note: "Élu en janvier 2022 (site officiel de la mairie)." },
  "Pout|Thiès": { maire: "Malick Ndiaye", note: "Sources divergentes (un autre nom, Moustapha Sarr, a aussi été relevé) — à reconfirmer." },
  "Bignona|Bignona": { maire: "Bacary Diatta", note: "Élu en janvier 2022, installé le 8 février 2022.", referent: "Seydou Badiane, Papi Faye" },
  "Kafountine|Bignona": { maire: "David Diatta", note: "Élu en janvier 2022." },
  "Diouloulou|Bignona": { maire: "Yaya Diatta", note: "Succède à Malang Thiam, décédé en cours de mandat." },
  "Kounkané|Vélingara": { maire: "Siradio Dia", note: "Élu en janvier 2022." },
  "Matam|Matam": { maire: "Mamadou Mory Diaw", note: "Source à recouper (homonymie possible avec d'autres localités hors Sénégal)." },
  "Ourossogui|Matam": { maire: "Moussa Bocar Thiam", note: "Source à recouper." },
  "Podor|Podor": { maire: "Mamadou Racine Sy", note: "Élu en janvier 2022." },
  "Dagana|Dagana": { maire: "Oumar Sarr", note: "En poste de longue date (depuis 1996 selon Wikipédia) — mandat 2022 à reconfirmer." },
  "Linguère|Linguère": { maire: "Aly Ngouille Ndiaye", note: "Source à recouper.", referent: "Ousmane Ndiaye" },
  "Dahra|Linguère": { maire: "Samba Ndiobène Ka", note: "Élu en janvier 2022." },
  "Kébémer|Kébémer": { maire: "Lamine Thiam", note: "Réélu en janvier 2022.", referent: "Babacar Niang" },
  "Bakel|Bakel": { maire: "Ibrahima Baba Salle", note: "Maire depuis 2014, réélu depuis." },
  "Kidira|Bakel": { maire: "Demba Thiam", note: "Source peu détaillée — à recouper." },
  "Goudiry|Goudiry": { maire: "Thiédel Diallo", note: "Source peu détaillée — à recouper." },
  "Sokone|Foundiougne": { maire: "Abdou Latif Coulibaly", note: "Élu en janvier 2022, installé le 12 février 2022." },
  "Diofior|Fatick": { maire: "Youssou Diome", note: "En poste depuis 2022." },
  "Bounkiling|Bounkiling": { maire: "Lamine Faty", note: "Source à recouper." },
  "Goudomp|Goudomp": { maire: "Abdoulaye Bosco Sadio", note: "Source à recouper." },
  "Marsassoum|Sédhiou": { maire: "Mamadou Gassama", note: "Source à recouper." },
  "Diamniadio|Rufisque": { maire: "Mamadou Moulaye Guèye", note: "Élu en janvier 2022 (3ᵉ mandat consécutif).", referent: "Cheikh Mayacine Diop" },
  "Bambey|Bambey": { maire: "Assane Dia", note: "Élu en janvier 2022.", referent: "Fallou Niasse" },
  "Gorée|Dakar": { maire: "Augustin Senghor", note: "Réélu en janvier 2022 (5ᵉ mandat consécutif)." },
  "Ouakam|Dakar": { maire: "Abdoul Aziz Guèye", note: "Élu en janvier 2022." },
  "Ngor|Dakar": { maire: "Magueye Ndiaye", note: "Élu en janvier 2022, a battu le maire sortant Amadou Guèye." },
  "Yoff|Dakar": { maire: "Seydina Issa Laye Samb", note: "Élu en janvier 2022." },
  "Grand Yoff|Dakar": {
    maire: "Madiop Diop",
    note: "Réélu en janvier 2022 (2ᵉ mandat), installé en février 2022.",
    referent: "Léna Elisabeth Mendy, Seny Diouf",
    documents: "Aucun document obtenu à ce stade — demande en cours",
    updated: "07/09/2026",
    suivi: "Suivi réel : lettre déposée le 28/08/2026, accusée réception par le secrétariat municipal. Deux réponses reçues (05/09 et 07/09) renvoyant vers le Receveur-percepteur au nom de la séparation ordonnateur/comptable, sans transmission de document. Une relance argumentée (continuité du service public, article 211 du Code général des Collectivités territoriales) est prévue avant l'échéance du 12/09/2026."
  },
  "Parcelles Assainies|Dakar": { maire: "Aboubacar Djamil Sané", note: "Élu en janvier 2022, installé le 9 février 2022." },
  "Médina|Dakar": { maire: "Bamba Fall", note: "Réélu en janvier 2022." },
  "Fann-Point E-Amitié|Dakar": { maire: "Dieynaba Bâ", note: "Succède à Palla Samb (élu en janvier 2022, décédé en mars 2023) depuis mai 2023." },
  "HLM|Dakar": { maire: "Moustapha Diop", note: "Élu en janvier 2022." },
  "Grand Dakar|Dakar": { maire: "Jean-Baptiste Diouf", note: "Réélu en janvier 2022 (3ᵉ mandat)." },
  "Hann Bel-Air|Dakar": { maire: "Babacar Mbengue", note: "Réélu en janvier 2022 (3ᵉ mandat).", referent: "Mamadou Dione" },
  "Dakar-Plateau|Dakar": { maire: "Alioune Ndoye", note: "Réélu en janvier 2022." },
  "Sicap-Liberté|Dakar": { maire: "Souleymane Camara", note: "Élu en janvier 2022." },
  "Colobane / Fass / Gueule Tapée|Dakar": { maire: "Abdoul Aziz Paye", note: "Élu en janvier 2022." },
  "Patte d'Oie|Dakar": { maire: "Abdoulaye Ka", note: "Succède à Maïmouna Dièye (mairesse élue en 2022, jusqu'en 2024).", referent: "Assane Koundou" },
  "Cambérène|Dakar": { maire: "Doune Pathé Mbengue", note: "Succède à Mame Amadou Samba (maire élu en février 2022)." },
  "Mermoz-Sacré-Cœur|Dakar": { maire: "Alioune Tall", note: "Succède à Barthélémy Dias (élu en février 2022, démissionnaire en mars 2022 après son élection comme maire de Dakar et député)." },
  "Dieuppeul-Derklé|Dakar": { maire: "Cheikh Guèye", note: "Élu en janvier 2022." },
  "Golf Sud|Guédiawaye": { maire: "Khadidiatou Diop Diouf", note: "Élue en janvier 2022, installée le 11 février 2022." },
  "Ndiarème Limamoulaye|Guédiawaye": { maire: "Baïdy Sèye", note: "Réélu en janvier 2022 (2ᵉ mandat) ; décédé en cours de mandat — successeur à identifier." },
  "Wakhinane Nimzatt|Guédiawaye": { maire: "Racine Talla", note: "Réélu en janvier 2022." },
  "Pikine Est|Pikine": { maire: "Issakha Diop", note: "Réélu en janvier 2022." },
  "Pikine Ouest|Pikine": { maire: "Cheikh Diop", note: "Élu en janvier 2022, en poste depuis mars 2022 ; a battu le maire sortant Pape Gorgui Ndong." },
  "Thiaroye-sur-Mer|Pikine": { maire: "El Hadj Mamadou Ndiaye", note: "Élu en janvier 2022 (premier mandat)." },
  "Mbao|Pikine": { maire: "Abdou Karim Sall", note: "Installé le 10 février 2022, succède à Abdoulaye Pouye.", referent: "Paul Diedhiou" },
  "Guinaw Rail Sud|Pikine": { maire: "Abdoulaye Diop", note: "Élu en janvier 2022." },
  "Dalifort|Pikine": { maire: "Mamadou Mbengue (dit Baye Diop)", note: "Réélu en janvier 2022." },
  "Djidah Thiaroye Kaw|Pikine": { maire: "Mamadou Guèye", note: "Élu en janvier 2022." },
  "Diamaguène / Sicap Mbao|Pikine": { maire: "Cheikh Aliou Bèye", note: "Élu en janvier 2022, a battu la maire sortante Coumba Ndoffène Fall." },
  "Thiaroye-Gare|Pikine": { maire: "Babacar Sène", note: "Source peu détaillée — à recouper." },
  "Diacksao|Pikine": { maire: "Moussa Fall", note: "Élu en janvier 2022 (commune de Tivaouane Diacksao), a battu la mairesse sortante Fatou Bintou Ndiaye." },
  "Guinaw Rail Nord|Pikine": { maire: "Waly Ndiaye", note: "Source peu détaillée — à recouper." },
  "Rufisque Nord|Rufisque": { maire: "Assane Kassé", note: "Élu en janvier 2022, a battu Mame Oumar Manga." },
  "Rufisque Ouest|Rufisque": { maire: "Alioune Mar", note: "Réélu en janvier 2022 (4ᵉ mandat) ; décédé en août 2024, successeur à identifier." },
  "Sébikhotane|Rufisque": { maire: "Abdoulaye Lô", note: "Maire sortant reconduit candidat en 2022 ; un changement (Alioune Pouye) est mentionné plus récemment — à reconfirmer." },
  "Sangalkam|Rufisque": { maire: "Alpha Bocar Khouma (dit Pape Sow)", note: "Élu en janvier 2022, installé le 10 février 2022." },
  "Yène|Rufisque": { maire: "El Hadji Massamba Mbengue", note: "Élu en janvier 2022." },
  "Bambylor|Rufisque": { maire: "Ngagne Diop", note: "Réélu en janvier 2022.", referent: "Adama Sow" },
  "Keur Massar Nord|Keur Massar": { maire: "Adama Sarr", note: "Élu en janvier 2022, premier maire de cette nouvelle commune.", referent: "Mame Saliou Wade" },
  "Malika|Keur Massar": { maire: "Momar Talla Gadiaga", note: "Réélu en janvier 2022 (3ᵉ mandat)." },
  "Yeumbeul Nord|Keur Massar": { maire: "Babacar Ndao", note: "Élu en janvier 2022." },
  "Yeumbeul Sud|Keur Massar": { maire: "Bara Gaye", note: "Réélu en janvier 2022, installé le 9 février 2022.", referent: "Idy Gaye Sow" },
  "Thiès Est|Thiès": { maire: "Ousmane Diagne", note: "Élu en janvier 2022 (coalition Yewwi Askan Wi)." },
  "Thiès Nord|Thiès": { maire: "Birame Souléye Diop", note: "Élu en janvier 2022 (coalition Yewwi Askan Wi)." },
  "Thiès Ouest|Thiès": { maire: "Mamadou Djité", note: "Élu en janvier 2022 (coalition Yewwi Askan Wi)." },
  "Fandène|Thiès": { maire: "Augustin Tine", note: "Source à recouper." },
  "Tassette|Thiès": { maire: "Mamadou Thiaw", note: "En poste depuis plus de dix ans, y compris le mandat 2022." },
  "Thiénaba|Thiès": { maire: "Talla Diagne", note: "Élu en janvier 2022." },
  "Keur Moussa|Thiès": { maire: "Momar Ciss", note: "Maire sortant reconduit en janvier 2022 (coalition BBY)." },
  "Ngoudiane|Thiès": { maire: "Mbaye Dione", note: "Réélu en janvier 2022 (3ᵉ mandat).", referent: "Ablaye Gning" },
  "Touba Toul|Thiès": { maire: "Ameth Dieye", note: "Élu en janvier 2022 (coalition Gox Yu Bess)." },
  "Saly|Mbour": { maire: "Ousmane Guèye", note: "Élu en janvier 2022 (Saly Portudal, coalition BBY)." },
  "Sindia|Mbour": { maire: "Thierno Diagne", note: "Réélu en janvier 2022 (coalition BBY).", referent: "Cheikhou Oumar Diallo" },
  "Nguékhokh|Mbour": { maire: "Pape Songué Diouf", note: "Source à recouper." },
  "Thiadiaye|Mbour": { maire: "Oumar Youm", note: "Source à recouper." },
  "Malicounda|Mbour": { maire: "Maguette Sène", note: "Réélu en janvier 2022 (2ᵉ mandat)." },
  "Diass|Mbour": { maire: "Mamadou Ndione", note: "Source à recouper." },
  "Sandiara|Mbour": { maire: "Aliou Gning", note: "Succède à Serigne Guèye Diop (élu en 2022, démissionnaire en 2024 pour devenir ministre)." },
  "Ndiaganiao|Mbour": { maire: "Tening Sène", note: "Élue en janvier 2022 (coalition BBY)." },
  "Fissel|Mbour": { maire: "Oumar Tine", note: "Commune de Fissel Mbadane — source à recouper." },
  "Nguéniène|Mbour": { maire: "Maguèye Ndao", note: "Élu en 2019 ; mandat 2022 à reconfirmer." },
  "Popenguine-Ndayane|Mbour": { maire: "Mamadou Mansour Thiandoum", note: "En poste depuis 2009 ; mandat 2022 à reconfirmer." },
  "Somone|Mbour": { maire: "El Hadj Boubacar Sadji", note: "Source à recouper." },
  "Meckhe|Tivaouane": { maire: "Magatte Wade", note: "Réélu en janvier 2022." },
  "Taïba Ndiaye|Tivaouane": { maire: "Assane Ndiaye", note: "Élu en janvier 2022, succède à Alé Lô (maire depuis 2014, décédé)." },
  "Pambal|Tivaouane": { maire: "Serigne Cheikh Mbacké Dione", note: "Source à recouper." },
  "Mérina Dakhar|Tivaouane": { maire: "Momar Sylla", note: "Succède à Aymérou Gningue (élu en janvier 2022, démissionnaire).", referent: "Cheikh Diop" },
  "Notto Gouye Diama|Tivaouane": { maire: "Maguette Mbaye", note: "Élu en janvier 2022." },
  "Darou Khoudoss|Tivaouane": { maire: "Magor Kane", note: "Source à recouper." },
  "Mont Rolland|Tivaouane": { maire: "Yves Lamine Ciss", note: "Réélu en janvier 2022 (3ᵉ mandat)." },
  "Koul|Tivaouane": { maire: "Modou Fall", note: "Source à recouper." },
  "Pékèsse|Tivaouane": { maire: "El Hadji Ndiaw Thiaw", note: "Élu en janvier 2022." },
  "Pire Goureye|Tivaouane": { maire: "Mamadou Ndoye Bane", note: "Installé le 10 février 2022, succède à Serigne Mboup." },
  "Niakhene|Tivaouane": { maire: "Moustapha Sylla", note: "Maire depuis 2014 (couvre le mandat 2022) ; a démissionné fin 2024, remplacé par Serigne Dieng." },
  "Méouane|Tivaouane": { maire: "Cheikh Sall", note: "Sources divergentes (Bara Ndiaye aussi mentionné) — à reconfirmer." },
  "Thilmakha|Tivaouane": { maire: "Cheikh Ibra Ndiaye (dit Lamp)", note: "Élu en janvier 2022." },
  "Chérif Lo|Tivaouane": { maire: "Ousmane Sarr", note: "Source à recouper." },
  "Mbayène|Tivaouane": { maire: "Masse Guèye", note: "Source à recouper." },
  "Touba Mosquée|Mbacké": { maire: "Abdoul Ahad Ka (dit Abdou Lahat Ka)", note: "Élu en janvier 2022, toujours en poste ; premier maire de Touba depuis 2014." },
  "Touba Mboul|Mbacké": { maire: "Mansour Niang", note: "Élu en 2014 ; mandat 2022 à reconfirmer." },
  "Kael|Mbacké": { maire: "El Hadji Ba", note: "Mandat 2022 à reconfirmer." },
  "Ndoulo|Diourbel": { maire: "Mamadou Kany Beye", note: "Source à recouper." },
  "Touré Mbonde|Diourbel": { maire: "Ibra Kane", note: "En poste depuis novembre 2022 au moins." },
  "Ngohé|Diourbel": { maire: "François Fall", note: "Source à recouper." },
  "Patar|Diourbel": { maire: "Aliou Diallo", note: "Source à recouper." },
  "Lambaye|Bambey": { maire: "Assane Ndiaye", note: "Élu en janvier 2022 ; un autre nom (Cheikh Ndiaye) est aussi mentionné ailleurs — à reconfirmer." },
  "Baba Garage|Bambey": { maire: "Modou Sarr Ndiaye", note: "Source à recouper." },
  "Ndangalma|Bambey": { maire: "Mor Ngom", note: "Élu en 2022, à l'unanimité des conseillers." },
  "Sakal|Louga": { maire: "Ousmane Samba Dieng", note: "Élu en janvier 2022." },
  "Léona|Louga": { maire: "Mamadou Bâ", note: "Source à recouper." },
  "Coki|Louga": { maire: "Cellé Ndiaye", note: "Source à recouper." },
  "Darou Mousty|Kébémer": { maire: "Madiop Bitèye", note: "Réélu en janvier 2022." },
  "Guéoul|Kébémer": { maire: "Serigne Mbaye Dia", note: "Source à recouper." },
  "Sagatta Gueth|Kébémer": { maire: "El Hadji Amar Lô (dit Gaydel)", note: "En poste en 2022." },
  "Ndande|Kébémer": { maire: "Adama Fall", note: "Source à recouper." },
  "Ngourane Ouolof|Kébémer": { maire: "Maodo Diop", note: "Source à recouper." },
  "Barkédji|Linguère": { maire: "Ousmane Samba Sow (dit Sambéré)", note: "Élu en janvier 2022." },
  "Yang-Yang|Linguère": { maire: "Mohamed Sène", note: "Source à recouper." },
  "Mbeuleukhé|Linguère": { maire: "Aliou Dia", note: "Source à recouper." },
  "Sagatta Djolof|Linguère": { maire: "Coumba Diaw", note: "Source à recouper." },
  "Gandon|Saint-Louis": { maire: "Khoudia Mbaye", note: "Source à recouper." },
  "Mpal|Saint-Louis": { maire: "Issa Diaw", note: "Source à recouper." },
  "Ross Béthio|Dagana": { maire: "Fally Seck", note: "Sources divergentes sur la date de prise de fonction — à reconfirmer." },
  "Rosso|Dagana": { maire: "Cheikh Gaye", note: "Source à recouper." },
  "Ndioum|Podor": { maire: "Cheikh Oumar Anne (aussi orthographié Hanne/Hann)", note: "Réélu en janvier 2022 (2ᵉ mandat)." },
  "Fanaye|Podor": { maire: "Aliou Gaye", note: "Source à recouper." },
  "Thilogne|Matam": { maire: "Mamadou Elimane Kane", note: "Installé en février 2022 (coalition Bunt Bi)." },
  "Bokidiawé|Matam": { maire: "Kalidou Wagué", note: "Source à recouper." },
  "Semmé|Kanel": { maire: "Habibou Thiembo", note: "En poste en 2022 ; emprisonné en février 2024 pour fraude présumée — successeur à identifier." },
  "Ranérou|Ranérou Ferlo": {
    maire: "Amadou Harouna Diallo (dit Gallo Diallo)",
    note: "Installé en février 2022, succède à Amadou Dawa Diallo (élu maire et président du Conseil départemental en janvier 2022, démissionnaire de la mairie pour incompatibilité de fonctions)."
  },
  "Diawara|Bakel": { maire: "Killé Sakho", note: "Maire depuis 2014 ; mandat 2022 à reconfirmer." },
  "Moudéry|Bakel": { maire: "Diakoye Tounkara", note: "Source à recouper." },
  "Koussanar|Tambacounda": { maire: "Boubacar Bâ", note: "Réélu (2ᵉ mandat), installé le 11 février 2022." },
  "Missirah|Tambacounda": { maire: "Amadou Bâ", note: "Élu en janvier 2022 (directeur du quotidien L'As)." },
  "Malem Niani|Koumpentoum": { maire: "Sirmang Sall", note: "Source à recouper." },
  "Kothiary|Goudiry": { maire: "Ismaïla Kaba", note: "Installé le 8 février 2022 (coalition Wallu Sénégal)." },
  "Bandafassi|Kédougou": { maire: "Cheikh Mbacké Sock", note: "Sources divergentes (Mamadou Yoro Bâ aussi mentionné) — à reconfirmer." },
  "Dindefelo|Kédougou": { maire: "Kikala Diallo", note: "Source à recouper." },
  "Fongolimbi|Kédougou": { maire: "Samba Camara", note: "Source à recouper." },
  "Tomboroncoto|Kédougou": { maire: "Nfally Camara", note: "Source à recouper." },
  "Khossanto|Saraya": { maire: "Mamady Cissokho", note: "Réélu, installé le 11 février 2022." },
  "Saraya|Saraya": { maire: "Sambaly Biagui", note: "Élu en janvier 2022 (coalition And Défar Sa Gokh), succède à Ngouda Soumaré." },
  "Bembou|Saraya": { maire: "Mady Danfakha", note: "Source à recouper." },
  "Dar Salam|Salémata": { maire: "Kamissa Camara", note: "Source à recouper." },
  "Dabo|Kolda": { maire: "Idrissa Baldé", note: "Source à recouper." },
  "Médina Yoro Foulah|Médina Yoro Foulah": { maire: "Kalidou Sy", note: "Réélu (2ᵉ mandat), installé le 9 février 2022." },
  "Diaobé-Kabendou|Vélingara": { maire: "Bambo Guirassy", note: "Élu en janvier 2022 (Pastef)." },
  "Pakour|Vélingara": { maire: "Diarga Sané", note: "Source à recouper." },
  "Djiredji|Sédhiou": { maire: "Mamadou-Lamine Diawara", note: "En poste en 2022 ; une source évoque son décès (sous le nom Malamine Diawara) — successeur à identifier." },
  "Tanaff|Goudomp": { maire: "Ibrahima Gomis", note: "En poste en juin 2022 ; un autre nom (Léonce Nzally) est mentionné en 2024 — à reconfirmer." },
  "Simbandi Balante|Goudomp": { maire: "Famara Kalbert Mané", note: "Réélu (3ᵉ mandat), installé le 15 février 2022." },
  "Madina Wandifa|Bounkiling": { maire: "Malang Seyni Faty", note: "Source à recouper (site officiel de la commune)." },
  "Diattacounda|Goudomp": { maire: "Djiby Sadio", note: "Commune remportée par BBY en janvier 2022 — source à recouper." },
  "Sindian|Bignona": { maire: "Ansou Sané (aussi Ansoumana Sané)", note: "Élu en janvier 2022, seule commune remportée par BBY dans le département de Bignona." },
  "Diembéring|Oussouye": { maire: "Demba Niassy", note: "Succède à Léopold Abba Diatta (élu en janvier 2022, décédé en cours de mandat)." },
  "Mlomp|Oussouye": { maire: "Sidy Eniap Sambou", note: "Source à recouper." },
  "Niaguis|Ziguinchor": { maire: "Victorine Ndèye", note: "Candidate BBY en 2022 — élection à reconfirmer.", referent: "Aliou Moussa Barro" },
  "Niakhar|Fatick": { maire: "Macodou Sène", note: "Installé en février 2022." },
  "Fimela|Fatick": { maire: "Karim Sène", note: "Maire depuis 2013, en poste durant le mandat 2022." },
  "Palmarin|Fatick": { maire: "Mame Singui Sarr", note: "Élu en janvier 2022." },
  "Tattaguine|Fatick": { maire: "Ibou Ndiaye", note: "Élu en janvier 2022, a battu le maire sortant Déthié Diouf." },
  "Diarrère|Fatick": { maire: "Thérèse Faye Diouf", note: "Réélue en janvier 2022 (2ᵉ mandat)." },
  "Toubacouta|Foundiougne": { maire: "Pape Seydou Dianko (aussi Nianko)", note: "Réélu en janvier 2022 (3ᵉ mandat, en poste depuis 2009)." },
  "Passy|Foundiougne": { maire: "Mame Baye Niass", note: "Sources divergentes (Adama Cissé aussi mentionné) — à reconfirmer." },
  "Karang Poste|Foundiougne": { maire: "Ibrahima Diop", note: "Élu en janvier 2022." },
  "Djilor|Foundiougne": { maire: "Lansana Sano", note: "Mandat débuté le 11 février 2022." },
  "Colobane|Gossas": { maire: "Mamadou Fall", note: "Source à recouper." },
  "Coubalan|Ziguinchor": { maire: "Mamadou Lamine Sora", note: "Installé en 2022 par le sous-préfet de Tenghory." },
  "Djinaky|Bignona": { maire: "Alphouseyni Diémé", note: "Source à recouper.", referent: "Arona Diedhiou" },
  "Gandiaye|Kaolack": { maire: "Pape Songdé Diop", note: "Source à recouper." },
  "Kahone|Kaolack": { maire: "Fatou Sène", note: "Élue en janvier 2022, première femme à la tête de la commune." },
  "Ndiaffate|Kaolack": { maire: "Aïssatou Ndiaye", note: "Réélue en janvier 2022 (2ᵉ mandat, coalition BBY)." },
  "Latmingué|Kaolack": { maire: "Macoumba Diouf", note: "Commune remportée par la coalition Ànd Nawlé Ànd Liguéey en janvier 2022." },
  "Keur Baka|Kaolack": { maire: "Mamadou Bâ", note: "Source à recouper." },
  "Sibassor|Kaolack": { maire: "Djiby Kalidou Bâ", note: "Source à recouper." },
  "Wack Ngouna|Nioro du Rip": { maire: "Amadou Lamine Dieng", note: "Réélu en janvier 2022 (environ 60% des voix)." },
  "Médina Sabakh|Nioro du Rip": { maire: "Ousmane Guèye", note: "Source ancienne (2017) — mandat 2022 à reconfirmer." },
  "Paoskoto|Nioro du Rip": { maire: "Momath Ba", note: "Succède à Aly Mané (maire sortant élu président du Conseil départemental de Nioro du Rip en janvier 2022)." },
  "Keur Madiabel|Nioro du Rip": { maire: "Abdoulaye Diatta", note: "Élu en janvier 2022 (coalition Union citoyenne Bunt Bi), bat le sortant Aliou Kébé." },
  "Mboss|Guinguinéo": { maire: "Mor Cissé", note: "Sources divergentes (Modou Diop Nguène aussi mentionné) — à reconfirmer." },
  "Ngathe Naoudé|Guinguinéo": { maire: "Yaye Fatou Diagne", note: "Source à recouper." },
  "Nganda|Kaffrine": { maire: "Baye Niasse Cissé", note: "Source à recouper." },
  "Birkilane|Birkelane": { maire: "Fallou Fall", note: "Source à recouper." },
  "Lour Escale|Koungheul": { maire: "Abdoulaye Ka", note: "Réélu en janvier 2022 (coalition BBY) ; décédé en 2025, successeur à identifier." },
  "Dianké Souf|Malem Hodar": { maire: "Seydou Ndiaye", note: "Source à recouper." },
  "Boulel|Kaffrine": { maire: "Ousmane Ndiaye", note: "Source à recouper." },
  "Gniby|Kaffrine": { maire: "Mansour Ndiaye", note: "Source à recouper.", referent: "Elhadji Diouf" },
  "Bonconto|Vélingara": { referent: "Hamady Cissé" },
  "Touba Lappé|Diourbel": { referent: "Elimane Diouf" },
  "Thiomby|Kaolack": { referent: "Odette Ngom" },
  "Taïba Niassène|Nioro du Rip": { referent: "Assane Diouf" },
  "Keur Massar Sud|Keur Massar": { referent: "Idrissa Diatta" },
  "Sinthiou Fissa|Bakel": { referent: "Amadou Konate" },
  "Keur Momar Sarr|Louga": { referent: "Khady Ba Sarr" },
};
